<?php

namespace Tests\Feature;

use Tests\TestCase;

// Regression test for a real bug caught while verifying this project's AWS
// deployment: GET / previously depended on view('welcome') (500'd on a
// missing Vite manifest), then — after that fix — still 500'd whenever the
// database was unreachable, because every routes/web.php route
// automatically gets Laravel's "web" middleware group, and several of its
// members (StartSession, ShareErrorsFromSession, and Laravel 13's CSRF
// middleware PreventRequestForgery) all touch the database-backed session
// even for a plain GET. Reproduced against a real RDS DNS outage locally.
class RootRouteTest extends TestCase
{
    protected function tearDown(): void
    {
        config(['database.connections.sqlite.database' => ':memory:']);
        parent::tearDown();
    }

    // public/index.html is gitignored (generated by bin/build-frontend.sh),
    // so this points the app at an empty temp directory rather than the
    // real public/ — deterministically exercises the JSON-ping fallback in
    // routes/web.php regardless of whether the frontend happens to be
    // built locally, and never touches the real project files (a first
    // version of this test wrote directly to public/index.html and, on
    // Windows, ended up deleting the real build output — BinaryFileResponse
    // appears to hold the file open long enough that tearDown's rewrite
    // silently failed).
    public function test_root_route_survives_an_unreachable_database(): void
    {
        $this->app->usePublicPath(sys_get_temp_dir() . '/vms-test-public-empty');

        config(['database.connections.sqlite.database' => '/nonexistent/path/does-not-exist.sqlite']);

        $response = $this->getJson('/');

        $response->assertOk()
            ->assertJson(['status' => 'ok']);
    }

    // The primary path in production/local dev (nginx or this same route
    // serves the built SPA) — the fallback above only matters when the
    // frontend hasn't been built at all. response()->file() returns a
    // Symfony BinaryFileResponse, which streams the file rather than
    // buffering it — getContent() is always false by design, so this
    // checks the Content-Type header (text/html) rather than the body,
    // which is enough to distinguish it from the JSON fallback response.
    public function test_root_route_serves_the_built_frontend_when_present(): void
    {
        $fakePublicPath = sys_get_temp_dir() . '/vms-test-public-' . uniqid();
        mkdir($fakePublicPath, recursive: true);
        file_put_contents(
            $fakePublicPath . '/index.html',
            '<!DOCTYPE html><html><body><div id="root"></div></body></html>'
        );

        $this->app->usePublicPath($fakePublicPath);

        $response = $this->get('/');

        $response->assertOk();
        $this->assertStringContainsString('text/html', $response->headers->get('Content-Type'));

        unlink($fakePublicPath . '/index.html');
        rmdir($fakePublicPath);
    }
}
